### ISSUE TITLE
Nice theme

### ISSUE THREAD

**Issue by obsy** [nutbolt/luci-theme-bootstrap#1]
Hi, very nice theme. But see for checkboxes: http://dl.dropbox.com/u/60469886/OpenWrt%20-%20LED%20Configuration%20-%20LuCI.png

**Comment by DavidMenting** [comment]
Solved. See https://github.com/Nut-Bolt/luci-theme-bootstrap/commit/c57e216c9038e9060658c34fba3221b3f21cb760

**Comment by obsy** [comment]
Thanks. Next - ntpd: http://dl.dropbox.com/u/60469886/OpenWrt%20-%20System%20-%20LuCI.png

**Comment by DavidMenting** [comment]
I can't get the NTPD-form to show up on my devices. How do I enable it? Or could you send me a saved .html from that page?

**Comment by obsy** [comment]
Hmm, this is standard page from system tab: http://dl.dropbox.com/u/60469886/OpenWrt%20-%20System%20-%20LuCI.html

**Comment by DavidMenting** [comment]
The built-in NTPD on my device is not available or turned of. Using your HTML I've been able to fix it like this:
https://github.com/Nut-Bolt/luci-theme-bootstrap/commit/f4454da943c7a9115367156eb6e427ab5062c2b7

**Comment by obsy** [comment]
Standard ar71xx trunk (on tplink), with latest luci. Your changes fixes the problem,  so this can be closed. Thanks again.

**Comment by DavidMenting** [comment]
Thanks for reporting. If you find any other issues I'd be pleased to hear.

**Comment by obsy** [comment]
BTW, this package should be marked by PKGARCH=:all in Makefile

**Comment by DavidMenting** [comment]
Where would that go, or could you send me a diff?

**Comment by obsy** [comment]
define Package/luci-theme-$(THEME_NAME)
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=Themes
  DEPENDS:=+luci-theme-base
  TITLE:=LuCI Theme - $(THEME_TITLE)
  URL:=http://nut-bolt.nl/
  PKGARCH:=all
endef

**Comment by DavidMenting** [comment]
That's a great tip! This means the final opkg packages is suited for all platforms, right?

**Comment by obsy** [comment]
Exactly. Downloaded package from your site can be installed on any platform.
